### ISSUE TITLE
Time required for execution

### ISSUE THREAD

**Issue by karthikbmk** [iit-cs429/assignments#7]
Will the assignment be evaluated on the speed of execution ?

It takes approx 1.5 minutes for the log generation of 83 queries. is this acceptable ?

**Comment by aronwc** [comment]
My code takes around 10 seconds, so I'm guessing you have some
inefficiencies here. Your code doesn't need to have the same running time,
but we may deduct a few points if the code is substantially inefficient
(e.g., some loop is quadratic instead of linear in the number of documents
or queries).

-Aron
